### ISSUE TITLE
Unobvious fiat currency option

### ISSUE THREAD

**Issue by tenacex** [wm-noble/send-btc#1]
I noticed that in the modal you can either select bitcoin, or a choosing from a list of fiat currencies as the currency to send. It is kinda not that obvious which is selected. I also think it could be improved by just having bitcoin be on the list of fiat currencies as well. DIP

**Comment by ouillie** [comment]
Well the widget only actually deals with Bitcoin. The fiat currencies are just for displaying current conversion rates to bitcoin. I forgot about the whole cross-domain request issue while I was making it though so the market rates feature is gonna take a little more thought.

**Comment by tenacex** [comment]
ohhhhh, I see, stupid me. Why can't you just enable cross origin sharing? And specify in the README that you need to add it to your webserver config?
